##### memory requirement numpy vs list

In [1]:
import numpy as np

li_arr=[i for i in range(100)]
np_arr=np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
#size of one element in numpy array
print(np_arr.itemsize)

#size of 100 element in numpy array
print(np_arr.itemsize * np_arr.size)

4
400


In [4]:
import sys

#size of 1 elem in list
print(sys.getsizeof(li_arr[0]))

#size of 100 ele in li
print(sys.getsizeof(1)*len(li_arr))

28
2800


##### numpy vs list speed by doing addition

In [11]:
import time
import numpy as np

size=100000

def add_using_list():
    t1=time.time()
    a=range(size)
    b=range(size)
    c=[a[i]+a[i] for i in range(size)]
    t2=time.time()
    return (t2-t1)

def add_using_numpy():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    
    t2=time.time()
    return (t2-t1)

t_l=add_using_list()
np_t=add_using_numpy()
print(t_l*1000,np_t*1000)  #millisecondsd

4.501986503601074 0.0


In [14]:
import time
print(time.time())  #return seconds till epoch

1761044759.2511854


In [15]:
import time
print(time.time())

1761044760.5781238


##### Why numpy is faster

In [18]:
import numpy as np

##### creating numpy arrays using n.array(array_like_object,dtype)

In [21]:
# using n.array(array_like_object,dtype)

a=[1,2,3]
b=np.array(a)
print(type(b))
c=np.array("abc")   #consider string as 1 unit
print(c)

d=np.array((1,2,3))   #tuple is ok
print(d)

<class 'numpy.ndarray'>
abc
[1 2 3]


In [22]:
a=[1,2,3,'a',5]
b=np.array(a)
print(b)     #numpy contain homogenous elements

['1' '2' '3' 'a' '5']


In [23]:
a=[1,2,3,'a',5]
b=np.array(a,dtype=int)
print(b)

ValueError: invalid literal for int() with base 10: 'a'

In [24]:
a=[1,2,3,4,5]
b=np.array(a,dtype=int)
print(b)

[1 2 3 4 5]


In [29]:
a=[1,2,3,4,5]
b=np.array(a*3)  #here mul list with int
print(b)
print(b*3)  #in case of numpy each elemnt will mul wit 3

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]
[ 3  6  9 12 15  3  6  9 12 15  3  6  9 12 15]


In [31]:
# creating numpy with each val=1......np.ones(dimension,dtype)

a=np.ones(5)
b=np.ones((2,3),dtype=int)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [32]:
# creating numpy with each val=0......np.zeros(dimension,dtype)

a=np.zeros(5)
b=np.zeros((2,3),dtype=int)
print(a)
print(b)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [40]:
# creating numpy with each val=0......np.full(dimension,fill_value,dtype)

a=np.full(5,fill_value=22)
b=np.full((2,3),2)
print(a)
print(b)

[22 22 22 22 22]
[[2 2 2]
 [2 2 2]]


In [42]:
# creating numpy with each val=1......np.empty(dimension,dtype)
#np.empty fill garbage values which afre already present in memory----faster than np.zeros or ones

a=np.empty(5)
b=np.empty((2,3),dtype=int)
print(a)
print(b)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 1 0]]


In [43]:
#np.arange(start,end,step,dtype).....like range()
a=np.arange(5,29,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27]


In [48]:
#np.linspace(start,end,np_ofvalues_you_want,dtype)
a=np.linspace(5,29,5)  #both start and step are included
print(a)

[ 5. 11. 17. 23. 29.]


In [47]:
a=np.linspace(5,29,10)
print(a)
common_diff=a[1]-a[0]
print(common_diff)

[ 5.          7.66666667 10.33333333 13.         15.66666667 18.33333333
 21.         23.66666667 26.33333333 29.        ]
2.666666666666666


In [49]:
a=np.linspace(5,29,6,endpoint=False) #end will be excluded
print(a)

[ 5.  9. 13. 17. 21. 25.]


In [50]:
a=np.identity(3)  #take single arg--always generate square matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
a=np.eye(3) 
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
a=np.eye(3,4)  #can take m,n as arg
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [55]:
# np.random.rand(dimension)

b=np.random.rand(3)  #create random numbers --(0,1)
b

array([0.70029742, 0.36691969, 0.03392559])

In [56]:
b=np.random.rand(3,4)
b

array([[0.75404121, 0.62557603, 0.75221352, 0.22284084],
       [0.91720112, 0.09178398, 0.21737849, 0.19322717],
       [0.02362285, 0.22976781, 0.90745542, 0.74960467]])

In [57]:
b=np.random.rand(10)*10
b

array([7.78130011, 7.08004896, 1.80045698, 1.9023792 , 5.64050326,
       4.12931701, 0.33587106, 3.11112988, 1.92036943, 9.97837186])

In [59]:
# np.random.randint(lowerbound,upperbound,dimension) both inclusive
# return int number in between (may be repeat)
b=np.random.randint(10,20)
b

19

In [69]:
b=np.random.randint(1,5,2)
b

array([2, 4])

In [70]:
b=np.random.randint(1,5,10)
b

array([4, 4, 1, 1, 3, 3, 3, 1, 4, 1])