In [1]:
import numpy as np

In [4]:
li = [i for i in range(1,6)]
arr=np.array(li)

In [5]:
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [13]:
print(arr.data)       # gives first byte ref
print(arr.shape)
print(arr.dtype)
print(arr.strides)     #no of byte skip to get new element


(5,)
int32
(4,)


In [17]:
print(li[3])
print(arr[3])

4
4


In [18]:
## indexing and slicing similar in both
arr[1:3]

array([2, 3])

In [10]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)

In [11]:
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
print(arr_2d.data)       # gives first byte ref
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)  # first value tell how many byte you have skip to go nexr row

(4, 4)
int32
(16, 4)


In [20]:
print(li_2d[2][1])
print(arr_2d[2][1])
#or
print(arr_2d[2,1])   #this give adv

10
10
10


In [21]:
#slicing in 2d is diff

In [23]:
print(li_2d[1][:3])
print(arr_2d[1,:3])

[5, 6, 7]
[5 6 7]


In [27]:
print(li_2d[0:3][2])   #we are doing first row slicing then coulumn
print(arr_2d[0:3][2]) #we are doing first row slicing then coulumn
print(arr_2d[0:3,2])  #here we doing slicing from both at same time

#as list not support above format so we cannot be able to acces some part of 2d arr as new arr directly by slicing

[9, 10, 11, 12]
[ 9 10 11 12]
[ 3  7 11]


In [28]:
print(li_2d[:3][3])

IndexError: list index out of range

In [31]:
#print(arr_2d[:3][3])     #error
print(arr_2d[:3,3])

[ 4  8 12]


In [35]:
print(arr_2d[2:4,1:3])

[[10 11]
 [14 15]]
