In [1]:
import numpy as np

In [2]:
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)

print(a)
print(b)
print(li)

[19  5 15 10 10]
[17 16 17  8  5]
[1, 2, 3, 4, 5]


In [3]:
#adding 1 to each

li=[i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [4]:
a=a+1

array([20,  6, 16, 11, 11])

In [5]:
c=a+b
c

array([36, 21, 32, 18, 15])

In [6]:
a*b

array([323,  80, 255,  80,  50])

In [7]:
a/b

array([1.11764706, 0.3125    , 0.88235294, 1.25      , 2.        ])

In [8]:
a//b

array([1, 0, 0, 1, 2])

In [9]:
a%b

array([ 2,  5, 15,  2,  0])

In [11]:
a-b

array([  2, -11,  -2,   2,   5])

In [12]:
a**b  ## a[i]**b[i]...element by element

array([ 1046123219, -2030932031, -1583482609,   100000000,      100000])

In [13]:
a.sum()

59

In [14]:
a.mean()

11.8

In [15]:
a.min()

5

In [16]:
a.argmin()  #give index of mkinimum

1

In [18]:
a.max()

19

In [19]:
a.argmax()

0

In [21]:
#for 2d

li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
print(arr_2d.sum())
print(arr_2d.mean())
print(arr_2d.min())
print(arr_2d.argmin())
print(arr_2d.max())

136
8.5
1
0
16


In [23]:
#relational and logical operations
a>b

array([ True, False, False,  True,  True])

In [24]:
a<b

array([False,  True,  True, False, False])

In [25]:
a==b

array([False, False, False, False, False])

In [29]:
#logical operations

a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
print(a)
print(b)

print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[0 0 1 1 1]
[1 1 0 1 0]
[ True  True  True  True  True]
[False False False  True False]
[ True  True False False False]


In [31]:
a=np.random.randint(0,2,(5,4))
b=np.random.randint(0,2,(5,4))
print(a)
print(b)

print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[[1 0 0 1]
 [0 1 1 1]
 [0 1 0 1]
 [0 1 0 1]
 [1 0 0 0]]
[[1 1 1 0]
 [1 0 1 1]
 [1 0 0 0]
 [1 0 1 0]
 [0 1 0 1]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]
 [ True  True False  True]]
[[ True False False False]
 [False False  True  True]
 [False False False False]
 [False False False False]
 [False False False False]]
[[False  True  True False]
 [ True False False False]
 [ True False  True False]
 [ True False  True False]
 [False  True  True  True]]


In [ ]:
#(& and -----both are different)

