In [3]:
import numpy as np

In [32]:
a=np.array(['a','z','n','m','t','l','j','e'])
b=np.random.randint(1,14,8)

print(a)
print(b)

['a' 'z' 'n' 'm' 't' 'l' 'j' 'e']
[ 5  8  5 12  7  4 13  5]


In [33]:
print(b>2)

[ True  True  True  True  True  True  True  True]


In [34]:
#extracting all elem >2

bool_ar=b>2
print(bool_ar)
new_ar=b[bool_ar]   #get true value only
print(new_ar)

[ True  True  True  True  True  True  True  True]
[ 5  8  5 12  7  4 13  5]


In [35]:
new_ar=b[b>2]
new_ar

array([ 5,  8,  5, 12,  7,  4, 13,  5])

In [36]:
new_ar=b[(b>2) & (b<10)]
new_ar

array([5, 8, 5, 7, 4, 5])

In [37]:
print(b)
c=b

[ 5  8  5 12  7  4 13  5]


In [38]:
c

array([ 5,  8,  5, 12,  7,  4, 13,  5])

In [39]:
#updating multiple elem at once 

c[:2]=10  #cannot do in normal list
c

array([10, 10,  5, 12,  7,  4, 13,  5])

In [40]:
print(c)
c[c>4]=100   #updating val based on condition
c

[10 10  5 12  7  4 13  5]


array([100, 100, 100, 100, 100,   4, 100, 100])

In [44]:
#t know index of values

print(b)
ind=np.where(b==100)
print(ind)

[100 100 100 100 100   4 100 100]
(array([0, 1, 2, 3, 4, 6, 7], dtype=int64),)


In [46]:
b=np.random.randint(1,15,8)

In [47]:
print(a)
print(b)

['a' 'z' 'n' 'm' 't' 'l' 'j' 'e']
[13  2  5  2 13  5 14 12]


In [50]:
ind=np.where(b>10)
print(ind)
print(a[ind])

(array([0, 4, 6, 7], dtype=int64),)
['a' 't' 'j' 'e']


In [51]:
#boolean indexing in 2d

x=np.random.randint(1,15,(5,6))
x

array([[ 1,  1,  9, 11,  5,  3],
       [ 9, 14,  6, 13,  9,  6],
       [10,  8, 10, 14, 13,  4],
       [ 9,  7, 12, 13, 13, 12],
       [ 5, 11,  9, 14, 10,  4]])

In [56]:
bool_arr=x>10
print(bool_arr)

[[False False False  True False False]
 [False  True False  True False False]
 [False False False  True  True False]
 [False False  True  True  True  True]
 [False  True False  True False False]]


In [59]:
ans=x[bool_arr]
ans             #get ouput in 1D

array([11, 14, 13, 14, 13, 12, 13, 13, 12, 11, 14])

In [60]:
#updating value at once
y=x
y[bool_arr]=100   #bool_arr=x>10
print(y)           #we can use bool_arr with any arr but size should same

[[  1   1   9 100   5   3]
 [  9 100   6 100   9   6]
 [ 10   8  10 100 100   4]
 [  9   7 100 100 100 100]
 [  5 100   9 100  10   4]]


In [61]:
z=np.random.randint(1,10,(2,2))
z

array([[5, 7],
       [8, 1]])

In [62]:
z_bool=np.array([[True, False],[False,True]])
z_bool

array([[ True, False],
       [False,  True]])

In [64]:
z1_bool=np.array([[True, False],[False,True],[False,True]])
z1_bool

array([[ True, False],
       [False,  True],
       [False,  True]])

In [68]:
print(z[z_bool])
#print(z[z1_bool]) #give error as dim not equal

[5 1]


In [70]:
#work on specific part of an 2d arr

print(x)

[[  1   1   9 100   5   3]
 [  9 100   6 100   9   6]
 [ 10   8  10 100 100   4]
 [  9   7 100 100 100 100]
 [  5 100   9 100  10   4]]


In [74]:
#let update value of 100 to 99 in column 4
boolar= x[:,4]==100
boolar

array([False, False,  True,  True, False])

In [75]:
x[boolar,4]=99   #boolar and column -row taken from boolarr

In [76]:
x

array([[  1,   1,   9, 100,   5,   3],
       [  9, 100,   6, 100,   9,   6],
       [ 10,   8,  10, 100,  99,   4],
       [  9,   7, 100, 100,  99, 100],
       [  5, 100,   9, 100,  10,   4]])

In [78]:
#let update value of 100 to 500 in column 1 to 3 AND row 2 to 5
boolarrr= x[1:6,0:4]==100
boolarrr

array([[False,  True, False,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False,  True, False,  True]])

In [81]:
x[boolarrr,(1:6,0:4)]=500
x
#we can work with specific row and specific column one at tme
#either row and column should be taken as whole

SyntaxError: invalid syntax (2570880366.py, line 1)

In [84]:
#let update value of 100 to 500 in column row 2
boolarrr= x[1,:]==100
boolarrr

array([False,  True, False,  True, False, False])

In [86]:
x[(1),boolarrr]=500
x

array([[  1,   1,   9, 100,   5,   3],
       [  9, 500,   6, 500,   9,   6],
       [ 10,   8,  10, 100,  99,   4],
       [  9,   7, 100, 100,  99, 100],
       [  5, 100,   9, 100,  10,   4]])

In [ ]:
# we can apply on bool for all 1d with eqaul values
#but for 2d we need to select aparticular row and a column at atime