In [1]:
import numpy as np

In [3]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
x-y

array([[-4, -5,  2],
       [-6, -1, -2],
       [ 0, -4, -2]])

In [5]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3))
print(x)
print(y)

[[7 5 2]
 [3 7 8]
 [9 6 8]]
[1 3 2]


In [6]:
x-y   #broadcasting

array([[6, 2, 0],
       [2, 4, 6],
       [8, 3, 6]])

In [14]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)
x-y

[[5 6 4]
 [6 3 7]
 [7 1 9]]
[[5 5]
 [1 4]
 [1 2]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [8]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)
x-y

[[7 2]
 [5 3]
 [1 2]]
[[1 9 6]
 [2 7 4]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [9]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)
y=np.transpose(y)  #we need to transpose either one

x-y

[[6 7]
 [3 9]
 [2 8]]
[[5 9 4]
 [6 2 7]]


array([[ 1,  1],
       [-6,  7],
       [-2,  1]])

In [10]:
import numpy as np

# Original array with 12 elements
original_array = np.arange(12)
print("Original array:\n", original_array)
print("Original array shape:", original_array.shape)

# Reshape the array to a 3x4 matrix
reshaped_array = original_array.reshape((3, 4))            #reshape return new arr and original array not be affected
print("\nReshaped array (3x4):\n", reshaped_array)
print("Reshaped array shape:", reshaped_array.shape)

# The original array remains unchanged
print("\nOriginal array after reshape:\n", original_array)   

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original array shape: (12,)

Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped array shape: (3, 4)

Original array after reshape:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
#Syntax: numpy.resize(array, new_shape) or array.resize(new_shape, refcheck=False)

import numpy as np

# Original array
my_array = np.array([0, 1, 2, 3, 4, 5])
print("Original array:\n", my_array)

# Resize to a larger size (3x3 = 9 elements)
# It will repeat elements from the original array
my_array.resize((3, 3))
print("\nArray after resizing to (3,3):\n", my_array)


# It will truncate the elements as it performs on orginal array

a=my_array.resize((2, 2))     #as it performs on orginal array so not return anything
print("\nArray after resizing to (2,2):\n", a)

Original array:
 [0 1 2 3 4 5]

Array after resizing to (3,3):
 [[0 1 2]
 [3 4 5]
 [0 0 0]]

Array after resizing to (2,2):
 None


In [17]:
x=np.random.randint(1,10,(1,3))
y=np.random.randint(1,10,(3,1))
print(x)
print(y)

print(x*y)    #broadcasting (here--we will not follow matrix approach too mult as notebook)

[[4 2 9]]
[[2]
 [9]
 [6]]
[[ 8  4 18]
 [36 18 81]
 [24 12 54]]


In [18]:
# for simple rule of matrix multiplication using np

import numpy as np

# Define two matrices
# A is a 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# B is a 3x2 matrix
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("Matrix A (shape", A.shape, "):\n", A)
print("\nMatrix B (shape", B.shape, "):\n", B)

# Perform matrix multiplication (2x3) @ (3x2) -> (2x2)
# The @ operator is the dedicated matrix multiplication operator
result = A @ B

print("\nResult of A @ B (shape", result.shape, "):\n", result)

Matrix A (shape (2, 3) ):
 [[1 2 3]
 [4 5 6]]

Matrix B (shape (3, 2) ):
 [[ 7  8]
 [ 9 10]
 [11 12]]

Result of A @ B (shape (2, 2) ):
 [[ 58  64]
 [139 154]]


In [19]:
x=np.random.randint(1,10,(1,3))
y=np.random.randint(1,10,(3,1))
print(x)
print(y)

print(x @ y) 

[[6 2 7]]
[[1]
 [3]
 [8]]
[[68]]


In [20]:
def multiply_matrices(A, B):
    """
    Multiplies two matrices A and B represented as nested lists.
    """
    # Get dimensions
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    # Check if matrices can be multiplied
    # The number of columns in A must equal the number of rows in B
    if cols_A != rows_B:
        print("Error: Matrices cannot be multiplied.")
        print(f"Matrix A columns ({cols_A}) != Matrix B rows ({rows_B})")
        return None

    # Initialize the result matrix C with zeros.
    # Dimensions will be rows_A x cols_B
    C = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # --- The Core Multiplication Logic ---
    # Iterate through each row of A
    for i in range(rows_A):
        # Iterate through each column of B
        for j in range(cols_B):
            # Iterate through each row of B (or col of A)
            for k in range(cols_A):  # or range(rows_B)
                # This is the dot product calculation
                C[i][j] += A[i][k] * B[k][j]

    return C

# --- Example Usage ---

# A is a 2x3 matrix
A = [[1, 2, 3],
     [4, 5, 6]]

# B is a 3x2 matrix
B = [[7, 8],
     [9, 10],
     [11, 12]]

print("Matrix A (2x3):\n", A)
print("\nMatrix B (3x2):\n", B)

# Perform matrix multiplication
# The result will be a 2x2 matrix
result = multiply_matrices(A, B)

if result:
    print("\nResult of A x B (2x2):\n", result)

# Let's pretty-print the result
if result:
    print("\nPretty-printed result:")
    for row in result:
        print(row)

Matrix A (2x3):
 [[1, 2, 3], [4, 5, 6]]

Matrix B (3x2):
 [[7, 8], [9, 10], [11, 12]]

Result of A x B (2x2):
 [[58, 64], [139, 154]]

Pretty-printed result:
[58, 64]
[139, 154]
